lang: en-US
title: Alexander Pyatkin
email: aspyatkin@gmail.com
description: >
    Hello there!
    My name is Alexander Pyatkin.
    I come from Samara, Russia.
    I work at Indigo Byte Systems, LLC on Dr.Explain and Tiwri.com.
baseurl: ""
url: "https://aspyatkin.com"
github_username:  aspyatkin

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

timezone: Europe/Samara

author: aspyatkin

disqus:
    shortname: aspyatkindotcom

google_analytics: UA-90317412-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - script
  - logs
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
