# Site settings
title: Alexander Pyatkin
description: |
    Hello there!
    My name is Alexander Pyatkin.
    I come from Samara, Russia.
    I work at Indigo Byte Systems, LLC on Dr.Explain and Tiwri.com.
baseurl: ""
url:
    development: https://aspyatkin.dev
    production: https://aspyatkin.com

twitter_username: aspyatkin
github_username:  aspyatkin

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - logs
  - letsencrypt